language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t brandowagner/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true brandowagner/docker-react npm run test